<br>
<div class="card">
    <img src="images/footer.png" height = 230; class="card-img">
    <div class="card-img-overlay">
        <div class="row">
            <div class="col-lg-9"></div>
            <div class="col-lg-3">
                <div class="card bg-light mb-3" style="max-width: 50%">
                    <div class="card-body">
                        <p style="text-align: left; font-size: 10px">
                            <b>Johannes Fog A/S</b>
                            <br>
                            Adresse: Firskovvej 20 - 2800 Lyngby
                            <br>
                            CVR-nr.: 16314439
                            <br>
                            Tlf.: +45 32-70-54-40
                            <br>
                            <br>
                            <b>Vores email: info@johannesfog.dk</b>
                            <a href="#"></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>